name: Firebase Deploy (DEV)

on:
  push:
    branches:
      - develop
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_STREAMPOLL_DEV_B2F18 }}'
          channelId: live
          projectId: streampoll-dev-b2f18
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
