name: Firebase Preview (PROD)

on:
  pull_request:
    branches: 
      - master

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_STREAMPOLL_CF56B }}'
          projectId: streampoll-cf56b
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
