name: Preview (DEV)

on:
  pull_request:
    branches: 
      - develop


jobs:
  'Firebase Pipeline':
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_STREAMPOLL_DEV_B2F18 }}'
          projectId: streampoll-dev-b2f18
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
