name: Deploy (PROD)

on:
  push:
    branches:
      - master
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CLI
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          PROJECT_ID: streampoll-cf56b
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          REACT_APP_BRANCH: "${{ github.ref }}"
          REACT_APP_COMMIT_SHA: ${{ github.sha }}"

