name: Deploy (DEV)

on:
  push:
    branches:
      - develop
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CLI
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          PROJECT_ID: streampoll-dev-b2f18
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          REACT_APP_BUILD_INFO: "[${{ github.ref }}] ${{ github.sha }}"

