name: Deploy to Live Channel

on:
  push:
    branches: 
      - develop

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_STREAMPOLL_CF56B }}"
          projectId: streampoll-dev-b2f18
          channelId: live