name: Firebase Deploy (DEV)

on:
  push:
    branches:
      - develop
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Function Dependencies
        run: cd api && npm install
      - name: Deploy functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          PROJECT_ID: streampoll-dev-b2f18
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

